# Generated by Django 3.2.12 on 2024-01-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('indroduction', models.TextField(null=True)),
                ('is_popular', models.BooleanField(default=False, null=True)),
                ('upload_date', models.DateTimeField()),
                ('image', models.ImageField(null=True, upload_to='newproducts')),
            ],
        ),
    ]
