# Generated by Django 5.0 on 2024-01-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_blog_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='indroduction',
        ),
    ]
