# Generated by Django 3.2.12 on 2024-01-26 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20240126_0628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
