# Generated by Django 5.0 on 2024-01-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.TextField(null=True),
        ),
    ]
