# Generated by Django 3.2.12 on 2024-01-24 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_delete_contact'),
        ('recipe', '0004_auto_20240124_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
