# Generated by Django 5.0 on 2024-01-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_remove_recipeingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.TimeField(null=True),
        ),
    ]
