# Generated by Django 3.2.12 on 2024-01-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_recipe_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='product',
        ),
    ]
