# Generated by Django 5.0 on 2024-01-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20240126_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='vedio',
            field=models.URLField(null=True),
        ),
    ]
