# Generated by Django 5.0 on 2024-01-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_recipe_vedio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='vedio',
        ),
    ]
