# Generated by Django 3.2.12 on 2023-12-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_banner_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='banner_area',
            name='deal',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='banner_area',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='banner_area',
            name='image',
            field=models.ImageField(null=True, upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='banner_area',
            name='link',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='banner_area',
            name='sale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='banner_area',
            name='title',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
