# Generated by Django 3.2.12 on 2023-12-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20231229_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='discount',
        ),
    ]
