# Generated by Django 3.2.12 on 2023-12-30 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_latestproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner_area',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='banner_area',
            name='link',
        ),
        migrations.RemoveField(
            model_name='banner_area',
            name='sale',
        ),
        migrations.AddField(
            model_name='banner_area',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.categories'),
        ),
    ]
