# Generated by Django 3.2.12 on 2023-12-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20231230_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='categoryname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
