# Generated by Django 3.2.12 on 2024-01-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20240101_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='newproducts'),
        ),
    ]
