# Generated by Django 5.0 on 2024-01-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_delete_latestproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_Dealsoftheday',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
