# Generated by Django 5.0 on 2024-01-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_is_dealsoftheday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='banner_area',
        ),
    ]
