# Generated by Django 3.2.12 on 2024-01-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_remove_cart_product_remove_cart_product_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=500)),
                ('messege', models.TextField()),
            ],
        ),
    ]
