# Generated by Django 5.0 on 2024-01-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
